spring:
  datasource: #mysql配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.159.184.58:3306/origin_admin_pro?useUnicode=true&characterSetServer=utf8mb4&autoReconnect=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: HWK33952938hwk

  data: #redis配置
    redis:
      host: 139.159.184.58      #IP
      port: 6379                #端口
      password: HWK33952938hwk  #密码
      database: 5               #库
      connect-timeout: 10s      #连接超时时间
      lettuce:                  #lettuce redis客户端配置
        pool:                   #连接池配置
          max-active: 10        #连接池最大连接数 默认 8
          max-wait: 200s        #连接池最大阻塞等待时间  默认 -1
          max-idle: 10          #连接池中最大空闲连接   默认 8
          min-idle: 0           #连接冲中最小空闲连接   默认  0

mybatis-plus: #mybaits-plus配置
  #xml 文件路径
  mapper-locations: classpath:mapper/*.xml
  #实体类路径
  # 数据库相关配置
  global-config:
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", U        UID:"全局唯一ID UUID";
      id-type: AUTO
      # 逻辑删除
      logic-delete-value: 0
      logic-not-delete-value: 1
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false



springdoc: #springdoc文档
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    # 持久化认证数据.如果设置为true,它会保留授权数并且不会再浏览器关闭/刷新时丢失
    persist-authorization: true
  api-docs:
    path: /v3/api-docs
    # 是否开启接口文档
    enabled: true


knife4j: # knife4j的增强配置，不需要增强可以不配
  enable: true
  setting:
    language: zh_cn


security: #jwt配置
  jwt:
    iss-user: "kevin"
    secret-key: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg
    expire-at: 7200
    refresh-expire-at: 604800